force-app/main/default/objects/EmailBuilderAppSettings__mdt/EmailBuilderAppSettings__mdt.object-meta.xml
<CustomObject>
    <label>EmailBuilderAppSetting</label>
    <pluralLabel>EmailBuilderAppSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EmailBuilderAppSettings__mdt/fields/GTWFieldValue__c.field-meta.xml
<CustomField>
    <fullName>GTWFieldValue__c</fullName>
    <description>Value for GTW field like #### for accountType</description>
    <label>GTWFieldValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfigurationController.cls
public with sharing class ConfigurationController {
    public static Map<String, String> viewEmailBuilderAppSettings() {

        Map<String, String> mapEmailBuilderAppSettings = new Map<String, String>(); 

        List<EmailBuilderAppSettings__mdt> emailBuilderAppSettings =  new List<EmailBuilderAppSettings__mdt>();
        
        try{
            emailBuilderAppSettings = [SELECT MasterLabel, QualifiedApiName, GTWFieldValue__c FROM EmailBuilderAppSettings__mdt WITH SECURITY_ENFORCED];
        
            for (EmailBuilderAppSettings__mdt customSetting : emailBuilderAppSettings) {
                mapEmailBuilderAppSettings.put(customSetting.MasterLabel, customSetting.GTWFieldValue__c);
            }
        }catch(Exception e){
            System.debug('Exception:ConfigurationController:viewEmailBuilderAppSettings(): ' + e.getMessage());
        }
        return mapEmailBuilderAppSettings;
    }
}